app:
  serviceName: "ports-processor"
  logLevel: "debug"
  portsFilePath: "./ports.json"
db:
  name: ${DB_NAME}
  user: ${DB_USER}
  host: ${DB_HOST}
  password: ${DB_PASSWORD}
  schema: ${DB_SCHEMA}
  port: 5432
  logMode: true
  sslMode: "disable"
  connectionPool:
    maxOpenConnections: 30
    maxIdleConnections: 10
    maxIdleTime: 30
    maxLifeTime: 3600
    timeout: 30
  portsTableName: ${PORTS_TABLE_SCHEMA}
  migrationPath: "./scripts"