app:
  serviceName: "ports-processor"
  logLevel: "debug"
  portsFilePath: "./data/ports.json"
db:
  name: "ports_db"
  user: "postgres"
  host: "localhost"
  password: "mySuperSecretPassword"
  schema: "public"
  port: 5432
  logMode: true
  sslMode: "disable"
  connectionPool:
    maxOpenConnections: 30
    maxIdleConnections: 10
    maxIdleTime: 30
    maxLifeTime: 3600
    timeout: 30
  migrationPath: "./internal/app/db/migrations/scripts"